# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - postgresql

before_install:
  - psql -c 'create database grabber;' -U postgres

# Отправлять уведомление на почту nesterenko-nikita@bk.ru если сборка упала
notifications:
  email:
    recipients:
      - nesterenko-nikita@bk.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="75a3c18b-fec3-4c97-8090-34931a4d00a5"